-- ============================================================
-- 0001_tables.sql
-- Core tables, built in dependency order (no forward references)
-- ============================================================

-- ---------- profiles ----------
-- Extends auth.users with app-specific fields (role, display name).
-- Row is created manually per user (only 2 users, Admin + Staff).
create table if not exists profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  name text not null,
  email text not null,
  role text not null check (role in ('Admin', 'Staff')),
  created_at timestamptz not null default now()
);

-- ---------- products ----------
create table if not exists products (
  id uuid primary key default gen_random_uuid(),
  product_name text not null,
  barcode text unique,
  category text,
  purchase_price numeric(10, 2) not null default 0,
  selling_price numeric(10, 2) not null default 0,
  discount numeric(10, 2) not null default 0,
  offer text,
  current_stock integer not null default 0,      -- intentionally NO check >= 0 (negative stock allowed, see triggers)
  minimum_stock integer not null default 5,
  image text,                                     -- Supabase Storage public URL
  status text not null default 'active' check (status in ('active', 'inactive')),
  created_at timestamptz not null default now()
);

create index if not exists idx_products_barcode on products(barcode);
create index if not exists idx_products_stock on products(current_stock);

-- ---------- customers ----------
create table if not exists customers (
  id uuid primary key default gen_random_uuid(),
  unique_customer_id text unique not null,   -- e.g. TC000001, generated by trigger below
  name text not null,
  phone text unique not null,
  email text,
  address text,
  birthday date,
  notes text,
  created_at timestamptz not null default now()
);

create index if not exists idx_customers_phone on customers(phone);

-- ---------- purchase_entries ----------
-- Whenever new stock comes in. Increases products.current_stock via trigger.
create table if not exists purchase_entries (
  id uuid primary key default gen_random_uuid(),
  product_id uuid not null references products(id) on delete restrict,
  purchase_price numeric(10, 2) not null,
  qty integer not null check (qty > 0),
  supplier text,
  bill_number text,
  date date not null default current_date,
  created_at timestamptz not null default now()
);

create index if not exists idx_purchase_entries_product on purchase_entries(product_id);
create index if not exists idx_purchase_entries_date on purchase_entries(date);

-- ---------- sales ----------
create table if not exists sales (
  id uuid primary key default gen_random_uuid(),
  invoice_no text unique not null,
  customer_id uuid references customers(id) on delete set null,
  date date not null default current_date,
  subtotal numeric(10, 2) not null default 0,
  discount numeric(10, 2) not null default 0,
  grand_total numeric(10, 2) not null default 0,
  payment_method text not null check (payment_method in ('Cash', 'UPI', 'Card')),
  notes text,
  created_at timestamptz not null default now()
);

create index if not exists idx_sales_date on sales(date);
create index if not exists idx_sales_customer on sales(customer_id);

-- ---------- sale_items ----------
-- Decreases products.current_stock via trigger (negative stock allowed).
create table if not exists sale_items (
  id uuid primary key default gen_random_uuid(),
  sale_id uuid not null references sales(id) on delete cascade,
  product_id uuid not null references products(id) on delete restrict,
  qty integer not null check (qty > 0),
  price numeric(10, 2) not null,
  discount numeric(10, 2) not null default 0,
  total numeric(10, 2) not null default 0,
  is_backorder boolean not null default false   -- set by trigger if stock went negative at sale time
);

create index if not exists idx_sale_items_sale on sale_items(sale_id);
create index if not exists idx_sale_items_product on sale_items(product_id);

-- ---------- expenses ----------
create table if not exists expenses (
  id uuid primary key default gen_random_uuid(),
  title text not null,
  category text not null,
  amount numeric(10, 2) not null,
  date date not null default current_date,
  note text,
  created_at timestamptz not null default now()
);

create index if not exists idx_expenses_date on expenses(date);

-- ---------- inquiries ----------
create table if not exists inquiries (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  phone text not null,
  required_product text not null,
  description text,
  status text not null default 'Pending'
    check (status in ('Pending', 'Ordered', 'Available', 'Called', 'Completed', 'Cancelled')),
  date date not null default current_date,
  followup_date date,
  remarks text,
  created_at timestamptz not null default now()
);

create index if not exists idx_inquiries_status on inquiries(status);

-- ---------- activity_logs ----------
-- Since Admin and Staff share full access (including delete), this is how you
-- answer "who deleted that?" after the fact.
create table if not exists activity_logs (
  id uuid primary key default gen_random_uuid(),
  table_name text not null,
  record_id uuid,
  action text not null check (action in ('INSERT', 'UPDATE', 'DELETE')),
  changed_by uuid references auth.users(id),
  old_data jsonb,
  new_data jsonb,
  created_at timestamptz not null default now()
);

create index if not exists idx_activity_logs_table on activity_logs(table_name, created_at desc);

-- ---------- settings ----------
-- Single-row table for shop-wide config (Phase 12, created now since it's trivial)
create table if not exists settings (
  id int primary key default 1 check (id = 1),  -- enforce single row
  business_name text default 'Toys Corner',
  gst text,
  logo text,
  whatsapp_number text,
  smtp_host text,
  smtp_port int,
  smtp_user text,
  daily_report_time time default '21:00',
  stock_reminder_enabled boolean default true,
  updated_at timestamptz not null default now()
);

insert into settings (id) values (1) on conflict (id) do nothing;
