-- ============================================================
-- 0006_seed.sql
-- Sample data so you can test the triggers immediately without
-- building any UI first (per the Phase 3 checkpoint in the build guide).
--
-- NOTE: run this AFTER creating your 2 real users in Supabase Auth,
-- then manually insert matching profiles rows (see bottom of this file).
-- ============================================================

-- Products
insert into products (id, product_name, barcode, category, purchase_price, selling_price, current_stock, minimum_stock)
values
  ('11111111-1111-1111-1111-111111111111', 'Remote Control Car', '8901111111111', 'Toys', 350, 599, 12, 5),
  ('22222222-2222-2222-2222-222222222222', 'Building Blocks Set', '8902222222222', 'Toys', 220, 399, 3, 10),
  ('33333333-3333-3333-3333-333333333333', 'Barbie Doll', '8903333333333', 'Toys', 180, 349, 0, 5)
on conflict (id) do nothing;

-- Customers (unique_customer_id auto-generated by trigger — leave it out)
insert into customers (id, name, phone, email, address)
values
  ('aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa', 'Rahul Sharma', '9998887771', 'rahul@example.com', 'Anand, Gujarat'),
  ('bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb', 'Priya Patel', '9998887772', 'priya@example.com', 'Vallabh Vidyanagar, Gujarat')
on conflict (id) do nothing;

-- Expenses
insert into expenses (title, category, amount, date)
values
  ('Electricity Bill', 'Electricity', 1200, current_date),
  ('Shop Rent', 'Rent', 8000, current_date - interval '5 days');

-- Inquiry
insert into inquiries (name, phone, required_product, status)
values
  ('Amit Verma', '9998887773', 'Hot Wheels Track Set', 'Pending');

-- ============================================================
-- MANUAL STEP after creating your 2 auth users in Supabase dashboard:
-- ============================================================
-- insert into profiles (id, name, email, role) values
--   ('<admin-auth-user-uuid>', 'Your Name', 'admin@toyscorner.com', 'Admin'),
--   ('<staff-auth-user-uuid>', 'Staff Name', 'staff@toyscorner.com', 'Staff');
